# Generated by Django 4.1.5 on 2023-01-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argaping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'verbose_name_plural': 'Propiedades'},
        ),
        migrations.RenameField(
            model_name='propiedad',
            old_name='calle',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='nro',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='moneda',
            field=models.CharField(default='ARS', max_length=5),
            preserve_default=False,
        ),
    ]
