# Generated by Django 4.1.5 on 2023-01-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argaping', '0003_remove_barrio_id_barrio_remove_filtro_id_filtro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
