# Generated by Django 4.1.6 on 2023-02-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argaping', '0007_propiedad_tipo_operacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='precio',
            new_name='precio_ars',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
