# Generated by Django 4.1.6 on 2023-02-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argaping', '0009_alter_propiedad_precio_ars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='filtro',
            name='nombre',
        ),
        migrations.AddField(
            model_name='filtro',
            name='tipo_operacion',
            field=models.CharField(default='alquiler', max_length=25),
            preserve_default=False,
        ),
    ]
