# Generated by Django 4.1 on 2022-09-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
            ],
        ),
    ]
