# Generated by Django 4.1.5 on 2023-01-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argaping', '0002_alter_propiedad_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrio',
            name='id_barrio',
        ),
        migrations.RemoveField(
            model_name='filtro',
            name='id_filtro',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='id_prop',
        ),
        migrations.AddField(
            model_name='barrio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filtro',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
