# Generated by Django 4.1.5 on 2023-01-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argaping', '0005_alter_propiedad_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
